name: Auto-sync fork

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency:
      group: fork-sync
      cancel-in-progress: true
    steps:
      - name: Sync default branch from upstream
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh repo sync "${GITHUB_REPOSITORY}" --branch main